### ISSUE TITLE
Pact checklist

### ISSUE THREAD

**Issue by sldblog** [ministryofjustice/hmpps-interventions-ui#38]
Copied from https://github.com/pact-foundation/pact_broker/wiki/Set-up-checklist

----

This is a high level check list of things that need to be done when setting up an integration to be tested with Pact using the Pact Broker. As there are many Pact implementations in different languages, you will need to consult the documentation for your language to find out how to implement each step. See [The steps to reaching Pact Nirvana](https://docs.google.com/document/d/e/2PACX-1vRf1kSDccImNipOOm1G-bjcSs-ifbZjf1v54K-dIcq8BLKeFPAAm_bf_p71UKqkRMIx30QWWL-kN8TI/pub) for an in depth explanation of the purpose of each step.

## Basic

This will get you to the stage where your consumer and provider have a pact that is generated and verified automatically, with a set up that allows you to introduce changes without breaking the provider build.

### Anyone

* [x] Set up an instance of the [Pact Broker](https://github.com/pact-foundation/pact_broker#for-reals)

### Consumer team

* [x] Write tests for the consumer that use the Pact mock provider (these generate the pact)
* [x] Add a task that only runs on the CI to publish the generated pacts to the Pact Broker (the Pact implementation for your language will provide this)
* [x] Configure the pacts to be published with a tag that is the dynamically determined name of the git/svn branch (eg. `master`, `feat-foo`)

### Provider team

See https://github.com/ministryofjustice/hmpps-interventions-service/issues/22

## Advanced

Skipping this part.
